"""
S&P 500 universe — full GICS classification.

Sourced from the Wikipedia S&P 500 constituents table (GICS sector +
sub-industry). Tickers normalised to yfinance form (BRK.B → BRK-B).
Names preserved from upstream.

`industry` holds the GICS Sub-Industry — the right granularity for
grouping comparable peers (e.g. Semiconductors vs Systems Software).
"""

from __future__ import annotations

from collections import OrderedDict
from dataclasses import dataclass


@dataclass(frozen=True)
class Stock:
    ticker: str
    name: str
    sector: str
    industry: str


SECTOR_ORDER: list[str] = [
    "Information Technology",
    "Communication Services",
    "Consumer Discretionary",
    "Consumer Staples",
    "Financials",
    "Health Care",
    "Industrials",
    "Energy",
    "Materials",
    "Real Estate",
    "Utilities",
]


UNIVERSE: list[Stock] = [

    # ── Information Technology (73) ──
    Stock("AAPL",  "Apple Inc.",                             "Information Technology", "Technology Hardware, Storage & Peripherals"),
    Stock("ACN",   "Accenture",                              "Information Technology", "IT Consulting & Other Services"),
    Stock("ADBE",  "Adobe Inc.",                             "Information Technology", "Application Software"),
    Stock("ADI",   "Analog Devices",                         "Information Technology", "Semiconductors"),
    Stock("ADSK",  "Autodesk",                               "Information Technology", "Application Software"),
    Stock("AKAM",  "Akamai Technologies",                    "Information Technology", "Internet Services & Infrastructure"),
    Stock("AMAT",  "Applied Materials",                      "Information Technology", "Semiconductor Materials & Equipment"),
    Stock("AMD",   "Advanced Micro Devices",                 "Information Technology", "Semiconductors"),
    Stock("ANET",  "Arista Networks",                        "Information Technology", "Communications Equipment"),
    Stock("APH",   "Amphenol",                               "Information Technology", "Electronic Components"),
    Stock("APP",   "AppLovin",                               "Information Technology", "Application Software"),
    Stock("AVGO",  "Broadcom",                               "Information Technology", "Semiconductors"),
    Stock("CDNS",  "Cadence Design Systems",                 "Information Technology", "Application Software"),
    Stock("CDW",   "CDW Corporation",                        "Information Technology", "Technology Distributors"),
    Stock("CIEN",  "Ciena",                                  "Information Technology", "Communications Equipment"),
    Stock("COHR",  "Coherent Corp.",                         "Information Technology", "Electronic Components"),
    Stock("CRM",   "Salesforce",                             "Information Technology", "Application Software"),
    Stock("CRWD",  "CrowdStrike",                            "Information Technology", "Systems Software"),
    Stock("CSCO",  "Cisco",                                  "Information Technology", "Communications Equipment"),
    Stock("CTSH",  "Cognizant",                              "Information Technology", "IT Consulting & Other Services"),
    Stock("DDOG",  "Datadog",                                "Information Technology", "Application Software"),
    Stock("DELL",  "Dell Technologies",                      "Information Technology", "Technology Hardware, Storage & Peripherals"),
    Stock("EPAM",  "EPAM Systems",                           "Information Technology", "IT Consulting & Other Services"),
    Stock("FFIV",  "F5, Inc.",                               "Information Technology", "Communications Equipment"),
    Stock("FICO",  "Fair Isaac",                             "Information Technology", "Application Software"),
    Stock("FSLR",  "First Solar",                            "Information Technology", "Semiconductors"),
    Stock("FTNT",  "Fortinet",                               "Information Technology", "Systems Software"),
    Stock("GDDY",  "GoDaddy",                                "Information Technology", "Internet Services & Infrastructure"),
    Stock("GEN",   "Gen Digital",                            "Information Technology", "Systems Software"),
    Stock("GLW",   "Corning Inc.",                           "Information Technology", "Electronic Components"),
    Stock("HPE",   "Hewlett Packard Enterprise",             "Information Technology", "Technology Hardware, Storage & Peripherals"),
    Stock("HPQ",   "HP Inc.",                                "Information Technology", "Technology Hardware, Storage & Peripherals"),
    Stock("IBM",   "IBM",                                    "Information Technology", "IT Consulting & Other Services"),
    Stock("INTC",  "Intel",                                  "Information Technology", "Semiconductors"),
    Stock("INTU",  "Intuit",                                 "Information Technology", "Application Software"),
    Stock("IT",    "Gartner",                                "Information Technology", "IT Consulting & Other Services"),
    Stock("JBL",   "Jabil",                                  "Information Technology", "Electronic Manufacturing Services"),
    Stock("KEYS",  "Keysight Technologies",                  "Information Technology", "Electronic Equipment & Instruments"),
    Stock("KLAC",  "KLA Corporation",                        "Information Technology", "Semiconductor Materials & Equipment"),
    Stock("LITE",  "Lumentum",                               "Information Technology", "Communications Equipment"),
    Stock("LRCX",  "Lam Research",                           "Information Technology", "Semiconductor Materials & Equipment"),
    Stock("MCHP",  "Microchip Technology",                   "Information Technology", "Semiconductors"),
    Stock("MPWR",  "Monolithic Power Systems",               "Information Technology", "Semiconductors"),
    Stock("MSFT",  "Microsoft",                              "Information Technology", "Systems Software"),
    Stock("MSI",   "Motorola Solutions",                     "Information Technology", "Communications Equipment"),
    Stock("MU",    "Micron Technology",                      "Information Technology", "Semiconductors"),
    Stock("NOW",   "ServiceNow",                             "Information Technology", "Systems Software"),
    Stock("NTAP",  "NetApp",                                 "Information Technology", "Technology Hardware, Storage & Peripherals"),
    Stock("NVDA",  "Nvidia",                                 "Information Technology", "Semiconductors"),
    Stock("NXPI",  "NXP Semiconductors",                     "Information Technology", "Semiconductors"),
    Stock("ON",    "ON Semiconductor",                       "Information Technology", "Semiconductors"),
    Stock("ORCL",  "Oracle Corporation",                     "Information Technology", "Application Software"),
    Stock("PANW",  "Palo Alto Networks",                     "Information Technology", "Systems Software"),
    Stock("PLTR",  "Palantir Technologies",                  "Information Technology", "Application Software"),
    Stock("PTC",   "PTC Inc.",                               "Information Technology", "Application Software"),
    Stock("Q",     "Qnity Electronics",                      "Information Technology", "Semiconductor Materials & Equipment"),
    Stock("QCOM",  "Qualcomm",                               "Information Technology", "Semiconductors"),
    Stock("ROP",   "Roper Technologies",                     "Information Technology", "Electronic Equipment & Instruments"),
    Stock("SMCI",  "Supermicro",                             "Information Technology", "Technology Hardware, Storage & Peripherals"),
    Stock("SNDK",  "Sandisk",                                "Information Technology", "Technology Hardware, Storage & Peripherals"),
    Stock("SNPS",  "Synopsys",                               "Information Technology", "Application Software"),
    Stock("STX",   "Seagate Technology",                     "Information Technology", "Technology Hardware, Storage & Peripherals"),
    Stock("SWKS",  "Skyworks Solutions",                     "Information Technology", "Semiconductors"),
    Stock("TDY",   "Teledyne Technologies",                  "Information Technology", "Electronic Equipment & Instruments"),
    Stock("TEL",   "TE Connectivity",                        "Information Technology", "Electronic Manufacturing Services"),
    Stock("TER",   "Teradyne",                               "Information Technology", "Semiconductor Materials & Equipment"),
    Stock("TRMB",  "Trimble Inc.",                           "Information Technology", "Application Software"),
    Stock("TXN",   "Texas Instruments",                      "Information Technology", "Semiconductors"),
    Stock("TYL",   "Tyler Technologies",                     "Information Technology", "Application Software"),
    Stock("VRSN",  "Verisign",                               "Information Technology", "Internet Services & Infrastructure"),
    Stock("WDAY",  "Workday, Inc.",                          "Information Technology", "Application Software"),
    Stock("WDC",   "Western Digital",                        "Information Technology", "Technology Hardware, Storage & Peripherals"),
    Stock("ZBRA",  "Zebra Technologies",                     "Information Technology", "Electronic Equipment & Instruments"),

    # ── Communication Services (23) ──
    Stock("CHTR",  "Charter Communications",                 "Communication Services", "Cable & Satellite"),
    Stock("CMCSA", "Comcast",                                "Communication Services", "Cable & Satellite"),
    Stock("DIS",   "Walt Disney Company (The)",              "Communication Services", "Movies & Entertainment"),
    Stock("EA",    "Electronic Arts",                        "Communication Services", "Interactive Home Entertainment"),
    Stock("FOX",   "Fox Corporation (Class B)",              "Communication Services", "Broadcasting"),
    Stock("FOXA",  "Fox Corporation (Class A)",              "Communication Services", "Broadcasting"),
    Stock("GOOG",  "Alphabet Inc. (Class C)",                "Communication Services", "Interactive Media & Services"),
    Stock("GOOGL", "Alphabet Inc. (Class A)",                "Communication Services", "Interactive Media & Services"),
    Stock("LYV",   "Live Nation Entertainment",              "Communication Services", "Movies & Entertainment"),
    Stock("META",  "Meta Platforms",                         "Communication Services", "Interactive Media & Services"),
    Stock("NFLX",  "Netflix",                                "Communication Services", "Movies & Entertainment"),
    Stock("NWS",   "News Corp (Class B)",                    "Communication Services", "Publishing"),
    Stock("NWSA",  "News Corp (Class A)",                    "Communication Services", "Publishing"),
    Stock("OMC",   "Omnicom Group",                          "Communication Services", "Advertising"),
    Stock("PSKY",  "Paramount Skydance Corporation",         "Communication Services", "Movies & Entertainment"),
    Stock("SATS",  "EchoStar",                               "Communication Services", "Wireless Telecommunication Services"),
    Stock("T",     "AT&T",                                   "Communication Services", "Integrated Telecommunication Services"),
    Stock("TKO",   "TKO Group Holdings",                     "Communication Services", "Movies & Entertainment"),
    Stock("TMUS",  "T-Mobile US",                            "Communication Services", "Wireless Telecommunication Services"),
    Stock("TTD",   "Trade Desk (The)",                       "Communication Services", "Advertising"),
    Stock("TTWO",  "Take-Two Interactive",                   "Communication Services", "Interactive Home Entertainment"),
    Stock("VZ",    "Verizon",                                "Communication Services", "Integrated Telecommunication Services"),
    Stock("WBD",   "Warner Bros. Discovery",                 "Communication Services", "Broadcasting"),

    # ── Consumer Discretionary (48) ──
    Stock("ABNB",  "Airbnb",                                 "Consumer Discretionary", "Hotels, Resorts & Cruise Lines"),
    Stock("AMZN",  "Amazon",                                 "Consumer Discretionary", "Broadline Retail"),
    Stock("APTV",  "Aptiv",                                  "Consumer Discretionary", "Automotive Parts & Equipment"),
    Stock("AZO",   "AutoZone",                               "Consumer Discretionary", "Automotive Retail"),
    Stock("BBY",   "Best Buy",                               "Consumer Discretionary", "Computer & Electronics Retail"),
    Stock("BKNG",  "Booking Holdings",                       "Consumer Discretionary", "Hotels, Resorts & Cruise Lines"),
    Stock("CCL",   "Carnival",                               "Consumer Discretionary", "Hotels, Resorts & Cruise Lines"),
    Stock("CMG",   "Chipotle Mexican Grill",                 "Consumer Discretionary", "Restaurants"),
    Stock("CVNA",  "Carvana",                                "Consumer Discretionary", "Automotive Retail"),
    Stock("DASH",  "DoorDash",                               "Consumer Discretionary", "Specialized Consumer Services"),
    Stock("DECK",  "Deckers Brands",                         "Consumer Discretionary", "Footwear"),
    Stock("DHI",   "D. R. Horton",                           "Consumer Discretionary", "Homebuilding"),
    Stock("DPZ",   "Domino's",                               "Consumer Discretionary", "Restaurants"),
    Stock("DRI",   "Darden Restaurants",                     "Consumer Discretionary", "Restaurants"),
    Stock("EBAY",  "eBay Inc.",                              "Consumer Discretionary", "Broadline Retail"),
    Stock("EXPE",  "Expedia Group",                          "Consumer Discretionary", "Hotels, Resorts & Cruise Lines"),
    Stock("F",     "Ford Motor Company",                     "Consumer Discretionary", "Automobile Manufacturers"),
    Stock("GM",    "General Motors",                         "Consumer Discretionary", "Automobile Manufacturers"),
    Stock("GPC",   "Genuine Parts Company",                  "Consumer Discretionary", "Distributors"),
    Stock("GRMN",  "Garmin",                                 "Consumer Discretionary", "Consumer Electronics"),
    Stock("HAS",   "Hasbro",                                 "Consumer Discretionary", "Leisure Products"),
    Stock("HD",    "Home Depot (The)",                       "Consumer Discretionary", "Home Improvement Retail"),
    Stock("HLT",   "Hilton Worldwide",                       "Consumer Discretionary", "Hotels, Resorts & Cruise Lines"),
    Stock("LEN",   "Lennar",                                 "Consumer Discretionary", "Homebuilding"),
    Stock("LOW",   "Lowe's",                                 "Consumer Discretionary", "Home Improvement Retail"),
    Stock("LULU",  "Lululemon Athletica",                    "Consumer Discretionary", "Apparel, Accessories & Luxury Goods"),
    Stock("LVS",   "Las Vegas Sands",                        "Consumer Discretionary", "Casinos & Gaming"),
    Stock("MAR",   "Marriott International",                 "Consumer Discretionary", "Hotels, Resorts & Cruise Lines"),
    Stock("MCD",   "McDonald's",                             "Consumer Discretionary", "Restaurants"),
    Stock("MGM",   "MGM Resorts",                            "Consumer Discretionary", "Casinos & Gaming"),
    Stock("NCLH",  "Norwegian Cruise Line Holdings",         "Consumer Discretionary", "Hotels, Resorts & Cruise Lines"),
    Stock("NKE",   "Nike, Inc.",                             "Consumer Discretionary", "Apparel, Accessories & Luxury Goods"),
    Stock("NVR",   "NVR, Inc.",                              "Consumer Discretionary", "Homebuilding"),
    Stock("ORLY",  "O’Reilly Automotive",                    "Consumer Discretionary", "Automotive Retail"),
    Stock("PHM",   "PulteGroup",                             "Consumer Discretionary", "Homebuilding"),
    Stock("POOL",  "Pool Corporation",                       "Consumer Discretionary", "Distributors"),
    Stock("RCL",   "Royal Caribbean Group",                  "Consumer Discretionary", "Hotels, Resorts & Cruise Lines"),
    Stock("RL",    "Ralph Lauren Corporation",               "Consumer Discretionary", "Apparel, Accessories & Luxury Goods"),
    Stock("ROST",  "Ross Stores",                            "Consumer Discretionary", "Apparel Retail"),
    Stock("SBUX",  "Starbucks",                              "Consumer Discretionary", "Restaurants"),
    Stock("TJX",   "TJX Companies",                          "Consumer Discretionary", "Apparel Retail"),
    Stock("TPR",   "Tapestry, Inc.",                         "Consumer Discretionary", "Apparel, Accessories & Luxury Goods"),
    Stock("TSCO",  "Tractor Supply",                         "Consumer Discretionary", "Other Specialty Retail"),
    Stock("TSLA",  "Tesla, Inc.",                            "Consumer Discretionary", "Automobile Manufacturers"),
    Stock("ULTA",  "Ulta Beauty",                            "Consumer Discretionary", "Other Specialty Retail"),
    Stock("WSM",   "Williams-Sonoma, Inc.",                  "Consumer Discretionary", "Homefurnishing Retail"),
    Stock("WYNN",  "Wynn Resorts",                           "Consumer Discretionary", "Casinos & Gaming"),
    Stock("YUM",   "Yum! Brands",                            "Consumer Discretionary", "Restaurants"),

    # ── Consumer Staples (36) ──
    Stock("ADM",   "Archer Daniels Midland",                 "Consumer Staples",       "Agricultural Products & Services"),
    Stock("BF-B",  "Brown–Forman",                           "Consumer Staples",       "Distillers & Vintners"),
    Stock("BG",    "Bunge Global",                           "Consumer Staples",       "Agricultural Products & Services"),
    Stock("CAG",   "Conagra Brands",                         "Consumer Staples",       "Packaged Foods & Meats"),
    Stock("CASY",  "Casey's",                                "Consumer Staples",       "Food Retail"),
    Stock("CHD",   "Church & Dwight",                        "Consumer Staples",       "Household Products"),
    Stock("CL",    "Colgate-Palmolive",                      "Consumer Staples",       "Household Products"),
    Stock("CLX",   "Clorox",                                 "Consumer Staples",       "Household Products"),
    Stock("COST",  "Costco",                                 "Consumer Staples",       "Consumer Staples Merchandise Retail"),
    Stock("CPB",   "Campbell's Company (The)",               "Consumer Staples",       "Packaged Foods & Meats"),
    Stock("DG",    "Dollar General",                         "Consumer Staples",       "Consumer Staples Merchandise Retail"),
    Stock("DLTR",  "Dollar Tree",                            "Consumer Staples",       "Consumer Staples Merchandise Retail"),
    Stock("EL",    "Estée Lauder Companies (The)",           "Consumer Staples",       "Personal Care Products"),
    Stock("GIS",   "General Mills",                          "Consumer Staples",       "Packaged Foods & Meats"),
    Stock("HRL",   "Hormel Foods",                           "Consumer Staples",       "Packaged Foods & Meats"),
    Stock("HSY",   "Hershey Company (The)",                  "Consumer Staples",       "Packaged Foods & Meats"),
    Stock("KDP",   "Keurig Dr Pepper",                       "Consumer Staples",       "Soft Drinks & Non-alcoholic Beverages"),
    Stock("KHC",   "Kraft Heinz",                            "Consumer Staples",       "Packaged Foods & Meats"),
    Stock("KMB",   "Kimberly-Clark",                         "Consumer Staples",       "Household Products"),
    Stock("KO",    "Coca-Cola Company (The)",                "Consumer Staples",       "Soft Drinks & Non-alcoholic Beverages"),
    Stock("KR",    "Kroger",                                 "Consumer Staples",       "Food Retail"),
    Stock("KVUE",  "Kenvue",                                 "Consumer Staples",       "Personal Care Products"),
    Stock("MDLZ",  "Mondelez International",                 "Consumer Staples",       "Packaged Foods & Meats"),
    Stock("MKC",   "McCormick & Company",                    "Consumer Staples",       "Packaged Foods & Meats"),
    Stock("MNST",  "Monster Beverage",                       "Consumer Staples",       "Soft Drinks & Non-alcoholic Beverages"),
    Stock("MO",    "Altria",                                 "Consumer Staples",       "Tobacco"),
    Stock("PEP",   "PepsiCo",                                "Consumer Staples",       "Soft Drinks & Non-alcoholic Beverages"),
    Stock("PG",    "Procter & Gamble",                       "Consumer Staples",       "Personal Care Products"),
    Stock("PM",    "Philip Morris International",            "Consumer Staples",       "Tobacco"),
    Stock("SJM",   "J.M. Smucker Company (The)",             "Consumer Staples",       "Packaged Foods & Meats"),
    Stock("STZ",   "Constellation Brands",                   "Consumer Staples",       "Distillers & Vintners"),
    Stock("SYY",   "Sysco",                                  "Consumer Staples",       "Food Distributors"),
    Stock("TAP",   "Molson Coors Beverage Company",          "Consumer Staples",       "Brewers"),
    Stock("TGT",   "Target Corporation",                     "Consumer Staples",       "Consumer Staples Merchandise Retail"),
    Stock("TSN",   "Tyson Foods",                            "Consumer Staples",       "Packaged Foods & Meats"),
    Stock("WMT",   "Walmart",                                "Consumer Staples",       "Consumer Staples Merchandise Retail"),

    # ── Financials (76) ──
    Stock("ACGL",  "Arch Capital Group",                     "Financials",             "Property & Casualty Insurance"),
    Stock("AFL",   "Aflac",                                  "Financials",             "Life & Health Insurance"),
    Stock("AIG",   "American International Group",           "Financials",             "Multi-line Insurance"),
    Stock("AIZ",   "Assurant",                               "Financials",             "Multi-line Insurance"),
    Stock("AJG",   "Arthur J. Gallagher & Co.",              "Financials",             "Insurance Brokers"),
    Stock("ALL",   "Allstate",                               "Financials",             "Property & Casualty Insurance"),
    Stock("AMP",   "Ameriprise Financial",                   "Financials",             "Asset Management & Custody Banks"),
    Stock("AON",   "Aon plc",                                "Financials",             "Insurance Brokers"),
    Stock("APO",   "Apollo Global Management",               "Financials",             "Asset Management & Custody Banks"),
    Stock("ARES",  "Ares Management",                        "Financials",             "Asset Management & Custody Banks"),
    Stock("AXP",   "American Express",                       "Financials",             "Consumer Finance"),
    Stock("BAC",   "Bank of America",                        "Financials",             "Diversified Banks"),
    Stock("BEN",   "Franklin Resources",                     "Financials",             "Asset Management & Custody Banks"),
    Stock("BK",    "BNY Mellon",                             "Financials",             "Asset Management & Custody Banks"),
    Stock("BLK",   "BlackRock",                              "Financials",             "Asset Management & Custody Banks"),
    Stock("BRK-B", "Berkshire Hathaway",                     "Financials",             "Multi-Sector Holdings"),
    Stock("BRO",   "Brown & Brown",                          "Financials",             "Insurance Brokers"),
    Stock("BX",    "Blackstone Inc.",                        "Financials",             "Asset Management & Custody Banks"),
    Stock("C",     "Citigroup",                              "Financials",             "Diversified Banks"),
    Stock("CB",    "Chubb Limited",                          "Financials",             "Property & Casualty Insurance"),
    Stock("CBOE",  "Cboe Global Markets",                    "Financials",             "Financial Exchanges & Data"),
    Stock("CFG",   "Citizens Financial Group",               "Financials",             "Regional Banks"),
    Stock("CINF",  "Cincinnati Financial",                   "Financials",             "Property & Casualty Insurance"),
    Stock("CME",   "CME Group",                              "Financials",             "Financial Exchanges & Data"),
    Stock("COF",   "Capital One",                            "Financials",             "Consumer Finance"),
    Stock("COIN",  "Coinbase",                               "Financials",             "Financial Exchanges & Data"),
    Stock("CPAY",  "Corpay",                                 "Financials",             "Transaction & Payment Processing Services"),
    Stock("EG",    "Everest Group",                          "Financials",             "Reinsurance"),
    Stock("ERIE",  "Erie Indemnity",                         "Financials",             "Insurance Brokers"),
    Stock("FDS",   "FactSet",                                "Financials",             "Financial Exchanges & Data"),
    Stock("FIS",   "Fidelity National Information Services", "Financials",             "Transaction & Payment Processing Services"),
    Stock("FISV",  "Fiserv",                                 "Financials",             "Transaction & Payment Processing Services"),
    Stock("FITB",  "Fifth Third Bancorp",                    "Financials",             "Regional Banks"),
    Stock("GL",    "Globe Life",                             "Financials",             "Life & Health Insurance"),
    Stock("GPN",   "Global Payments",                        "Financials",             "Transaction & Payment Processing Services"),
    Stock("GS",    "Goldman Sachs",                          "Financials",             "Investment Banking & Brokerage"),
    Stock("HBAN",  "Huntington Bancshares",                  "Financials",             "Regional Banks"),
    Stock("HIG",   "Hartford (The)",                         "Financials",             "Property & Casualty Insurance"),
    Stock("HOOD",  "Robinhood Markets",                      "Financials",             "Investment Banking & Brokerage"),
    Stock("IBKR",  "Interactive Brokers",                    "Financials",             "Investment Banking & Brokerage"),
    Stock("ICE",   "Intercontinental Exchange",              "Financials",             "Financial Exchanges & Data"),
    Stock("IVZ",   "Invesco",                                "Financials",             "Asset Management & Custody Banks"),
    Stock("JKHY",  "Jack Henry & Associates",                "Financials",             "Transaction & Payment Processing Services"),
    Stock("JPM",   "JPMorgan Chase",                         "Financials",             "Diversified Banks"),
    Stock("KEY",   "KeyCorp",                                "Financials",             "Regional Banks"),
    Stock("KKR",   "KKR & Co.",                              "Financials",             "Asset Management & Custody Banks"),
    Stock("L",     "Loews Corporation",                      "Financials",             "Multi-line Insurance"),
    Stock("MA",    "Mastercard",                             "Financials",             "Transaction & Payment Processing Services"),
    Stock("MCO",   "Moody's Corporation",                    "Financials",             "Financial Exchanges & Data"),
    Stock("MET",   "MetLife",                                "Financials",             "Life & Health Insurance"),
    Stock("MRSH",  "Marsh McLennan",                         "Financials",             "Insurance Brokers"),
    Stock("MS",    "Morgan Stanley",                         "Financials",             "Investment Banking & Brokerage"),
    Stock("MSCI",  "MSCI Inc.",                              "Financials",             "Financial Exchanges & Data"),
    Stock("MTB",   "M&T Bank",                               "Financials",             "Regional Banks"),
    Stock("NDAQ",  "Nasdaq, Inc.",                           "Financials",             "Financial Exchanges & Data"),
    Stock("NTRS",  "Northern Trust",                         "Financials",             "Asset Management & Custody Banks"),
    Stock("PFG",   "Principal Financial Group",              "Financials",             "Life & Health Insurance"),
    Stock("PGR",   "Progressive Corporation",                "Financials",             "Property & Casualty Insurance"),
    Stock("PNC",   "PNC Financial Services",                 "Financials",             "Diversified Banks"),
    Stock("PRU",   "Prudential Financial",                   "Financials",             "Life & Health Insurance"),
    Stock("PYPL",  "PayPal",                                 "Financials",             "Transaction & Payment Processing Services"),
    Stock("RF",    "Regions Financial Corporation",          "Financials",             "Regional Banks"),
    Stock("RJF",   "Raymond James Financial",                "Financials",             "Investment Banking & Brokerage"),
    Stock("SCHW",  "Charles Schwab Corporation",             "Financials",             "Investment Banking & Brokerage"),
    Stock("SPGI",  "S&P Global",                             "Financials",             "Financial Exchanges & Data"),
    Stock("STT",   "State Street Corporation",               "Financials",             "Asset Management & Custody Banks"),
    Stock("SYF",   "Synchrony Financial",                    "Financials",             "Consumer Finance"),
    Stock("TFC",   "Truist Financial",                       "Financials",             "Diversified Banks"),
    Stock("TROW",  "T. Rowe Price",                          "Financials",             "Asset Management & Custody Banks"),
    Stock("TRV",   "Travelers Companies (The)",              "Financials",             "Property & Casualty Insurance"),
    Stock("USB",   "U.S. Bancorp",                           "Financials",             "Diversified Banks"),
    Stock("V",     "Visa Inc.",                              "Financials",             "Transaction & Payment Processing Services"),
    Stock("WFC",   "Wells Fargo",                            "Financials",             "Diversified Banks"),
    Stock("WRB",   "W. R. Berkley Corporation",              "Financials",             "Property & Casualty Insurance"),
    Stock("WTW",   "Willis Towers Watson",                   "Financials",             "Insurance Brokers"),
    Stock("XYZ",   "Block, Inc.",                            "Financials",             "Transaction & Payment Processing Services"),

    # ── Health Care (58) ──
    Stock("A",     "Agilent Technologies",                   "Health Care",            "Life Sciences Tools & Services"),
    Stock("ABBV",  "AbbVie",                                 "Health Care",            "Biotechnology"),
    Stock("ABT",   "Abbott Laboratories",                    "Health Care",            "Health Care Equipment"),
    Stock("ALGN",  "Align Technology",                       "Health Care",            "Health Care Supplies"),
    Stock("AMGN",  "Amgen",                                  "Health Care",            "Biotechnology"),
    Stock("BAX",   "Baxter International",                   "Health Care",            "Health Care Equipment"),
    Stock("BDX",   "Becton Dickinson",                       "Health Care",            "Health Care Equipment"),
    Stock("BIIB",  "Biogen",                                 "Health Care",            "Biotechnology"),
    Stock("BMY",   "Bristol Myers Squibb",                   "Health Care",            "Pharmaceuticals"),
    Stock("BSX",   "Boston Scientific",                      "Health Care",            "Health Care Equipment"),
    Stock("CAH",   "Cardinal Health",                        "Health Care",            "Health Care Distributors"),
    Stock("CI",    "Cigna",                                  "Health Care",            "Health Care Services"),
    Stock("CNC",   "Centene Corporation",                    "Health Care",            "Managed Health Care"),
    Stock("COO",   "Cooper Companies (The)",                 "Health Care",            "Health Care Supplies"),
    Stock("COR",   "Cencora",                                "Health Care",            "Health Care Distributors"),
    Stock("CRL",   "Charles River Laboratories",             "Health Care",            "Life Sciences Tools & Services"),
    Stock("CVS",   "CVS Health",                             "Health Care",            "Health Care Services"),
    Stock("DGX",   "Quest Diagnostics",                      "Health Care",            "Health Care Services"),
    Stock("DHR",   "Danaher Corporation",                    "Health Care",            "Life Sciences Tools & Services"),
    Stock("DVA",   "DaVita",                                 "Health Care",            "Health Care Services"),
    Stock("DXCM",  "Dexcom",                                 "Health Care",            "Health Care Equipment"),
    Stock("ELV",   "Elevance Health",                        "Health Care",            "Managed Health Care"),
    Stock("EW",    "Edwards Lifesciences",                   "Health Care",            "Health Care Equipment"),
    Stock("GEHC",  "GE HealthCare",                          "Health Care",            "Health Care Equipment"),
    Stock("GILD",  "Gilead Sciences",                        "Health Care",            "Biotechnology"),
    Stock("HCA",   "HCA Healthcare",                         "Health Care",            "Health Care Facilities"),
    Stock("HSIC",  "Henry Schein",                           "Health Care",            "Health Care Distributors"),
    Stock("HUM",   "Humana",                                 "Health Care",            "Managed Health Care"),
    Stock("IDXX",  "Idexx Laboratories",                     "Health Care",            "Health Care Equipment"),
    Stock("INCY",  "Incyte",                                 "Health Care",            "Biotechnology"),
    Stock("IQV",   "IQVIA",                                  "Health Care",            "Life Sciences Tools & Services"),
    Stock("ISRG",  "Intuitive Surgical",                     "Health Care",            "Health Care Equipment"),
    Stock("JNJ",   "Johnson & Johnson",                      "Health Care",            "Pharmaceuticals"),
    Stock("LH",    "Labcorp",                                "Health Care",            "Health Care Services"),
    Stock("LLY",   "Lilly (Eli)",                            "Health Care",            "Pharmaceuticals"),
    Stock("MCK",   "McKesson Corporation",                   "Health Care",            "Health Care Distributors"),
    Stock("MDT",   "Medtronic",                              "Health Care",            "Health Care Equipment"),
    Stock("MRK",   "Merck & Co.",                            "Health Care",            "Pharmaceuticals"),
    Stock("MRNA",  "Moderna",                                "Health Care",            "Biotechnology"),
    Stock("MTD",   "Mettler Toledo",                         "Health Care",            "Life Sciences Tools & Services"),
    Stock("PFE",   "Pfizer",                                 "Health Care",            "Pharmaceuticals"),
    Stock("PODD",  "Insulet Corporation",                    "Health Care",            "Health Care Equipment"),
    Stock("REGN",  "Regeneron Pharmaceuticals",              "Health Care",            "Biotechnology"),
    Stock("RMD",   "ResMed",                                 "Health Care",            "Health Care Equipment"),
    Stock("RVTY",  "Revvity",                                "Health Care",            "Health Care Equipment"),
    Stock("SOLV",  "Solventum",                              "Health Care",            "Health Care Technology"),
    Stock("STE",   "Steris",                                 "Health Care",            "Health Care Equipment"),
    Stock("SYK",   "Stryker Corporation",                    "Health Care",            "Health Care Equipment"),
    Stock("TECH",  "Bio-Techne",                             "Health Care",            "Life Sciences Tools & Services"),
    Stock("TMO",   "Thermo Fisher Scientific",               "Health Care",            "Life Sciences Tools & Services"),
    Stock("UHS",   "Universal Health Services",              "Health Care",            "Health Care Facilities"),
    Stock("UNH",   "UnitedHealth Group",                     "Health Care",            "Managed Health Care"),
    Stock("VRTX",  "Vertex Pharmaceuticals",                 "Health Care",            "Biotechnology"),
    Stock("VTRS",  "Viatris",                                "Health Care",            "Pharmaceuticals"),
    Stock("WAT",   "Waters Corporation",                     "Health Care",            "Life Sciences Tools & Services"),
    Stock("WST",   "West Pharmaceutical Services",           "Health Care",            "Health Care Supplies"),
    Stock("ZBH",   "Zimmer Biomet",                          "Health Care",            "Health Care Equipment"),
    Stock("ZTS",   "Zoetis",                                 "Health Care",            "Pharmaceuticals"),

    # ── Industrials (79) ──
    Stock("ADP",   "Automatic Data Processing",              "Industrials",            "Human Resource & Employment Services"),
    Stock("ALLE",  "Allegion",                               "Industrials",            "Building Products"),
    Stock("AME",   "Ametek",                                 "Industrials",            "Electrical Components & Equipment"),
    Stock("AOS",   "A. O. Smith",                            "Industrials",            "Building Products"),
    Stock("AXON",  "Axon Enterprise",                        "Industrials",            "Aerospace & Defense"),
    Stock("BA",    "Boeing",                                 "Industrials",            "Aerospace & Defense"),
    Stock("BLDR",  "Builders FirstSource",                   "Industrials",            "Building Products"),
    Stock("BR",    "Broadridge Financial Solutions",         "Industrials",            "Data Processing & Outsourced Services"),
    Stock("CARR",  "Carrier Global",                         "Industrials",            "Building Products"),
    Stock("CAT",   "Caterpillar Inc.",                       "Industrials",            "Construction Machinery & Heavy Transportation Equipment"),
    Stock("CHRW",  "C.H. Robinson",                          "Industrials",            "Air Freight & Logistics"),
    Stock("CMI",   "Cummins",                                "Industrials",            "Construction Machinery & Heavy Transportation Equipment"),
    Stock("CPRT",  "Copart",                                 "Industrials",            "Diversified Support Services"),
    Stock("CSX",   "CSX Corporation",                        "Industrials",            "Rail Transportation"),
    Stock("CTAS",  "Cintas",                                 "Industrials",            "Diversified Support Services"),
    Stock("DAL",   "Delta Air Lines",                        "Industrials",            "Passenger Airlines"),
    Stock("DE",    "Deere & Company",                        "Industrials",            "Agricultural & Farm Machinery"),
    Stock("DOV",   "Dover Corporation",                      "Industrials",            "Industrial Machinery & Supplies & Components"),
    Stock("EFX",   "Equifax",                                "Industrials",            "Research & Consulting Services"),
    Stock("EME",   "Emcor",                                  "Industrials",            "Construction & Engineering"),
    Stock("EMR",   "Emerson Electric",                       "Industrials",            "Electrical Components & Equipment"),
    Stock("ETN",   "Eaton Corporation",                      "Industrials",            "Electrical Components & Equipment"),
    Stock("EXPD",  "Expeditors International",               "Industrials",            "Air Freight & Logistics"),
    Stock("FAST",  "Fastenal",                               "Industrials",            "Trading Companies & Distributors"),
    Stock("FDX",   "FedEx",                                  "Industrials",            "Air Freight & Logistics"),
    Stock("FIX",   "Comfort Systems USA",                    "Industrials",            "Construction & Engineering"),
    Stock("FTV",   "Fortive",                                "Industrials",            "Industrial Machinery & Supplies & Components"),
    Stock("GD",    "General Dynamics",                       "Industrials",            "Aerospace & Defense"),
    Stock("GE",    "GE Aerospace",                           "Industrials",            "Aerospace & Defense"),
    Stock("GEV",   "GE Vernova",                             "Industrials",            "Heavy Electrical Equipment"),
    Stock("GNRC",  "Generac",                                "Industrials",            "Electrical Components & Equipment"),
    Stock("GWW",   "W. W. Grainger",                         "Industrials",            "Industrial Machinery & Supplies & Components"),
    Stock("HII",   "Huntington Ingalls Industries",          "Industrials",            "Aerospace & Defense"),
    Stock("HON",   "Honeywell",                              "Industrials",            "Industrial Conglomerates"),
    Stock("HUBB",  "Hubbell Incorporated",                   "Industrials",            "Industrial Machinery & Supplies & Components"),
    Stock("HWM",   "Howmet Aerospace",                       "Industrials",            "Aerospace & Defense"),
    Stock("IEX",   "IDEX Corporation",                       "Industrials",            "Industrial Machinery & Supplies & Components"),
    Stock("IR",    "Ingersoll Rand",                         "Industrials",            "Industrial Machinery & Supplies & Components"),
    Stock("ITW",   "Illinois Tool Works",                    "Industrials",            "Industrial Machinery & Supplies & Components"),
    Stock("J",     "Jacobs Solutions",                       "Industrials",            "Construction & Engineering"),
    Stock("JBHT",  "J.B. Hunt",                              "Industrials",            "Cargo Ground Transportation"),
    Stock("JCI",   "Johnson Controls",                       "Industrials",            "Building Products"),
    Stock("LDOS",  "Leidos",                                 "Industrials",            "Diversified Support Services"),
    Stock("LHX",   "L3Harris",                               "Industrials",            "Aerospace & Defense"),
    Stock("LII",   "Lennox International",                   "Industrials",            "Building Products"),
    Stock("LMT",   "Lockheed Martin",                        "Industrials",            "Aerospace & Defense"),
    Stock("LUV",   "Southwest Airlines",                     "Industrials",            "Passenger Airlines"),
    Stock("MAS",   "Masco",                                  "Industrials",            "Building Products"),
    Stock("MMM",   "3M",                                     "Industrials",            "Industrial Conglomerates"),
    Stock("NDSN",  "Nordson Corporation",                    "Industrials",            "Industrial Machinery & Supplies & Components"),
    Stock("NOC",   "Northrop Grumman",                       "Industrials",            "Aerospace & Defense"),
    Stock("NSC",   "Norfolk Southern",                       "Industrials",            "Rail Transportation"),
    Stock("ODFL",  "Old Dominion",                           "Industrials",            "Cargo Ground Transportation"),
    Stock("OTIS",  "Otis Worldwide",                         "Industrials",            "Industrial Machinery & Supplies & Components"),
    Stock("PAYX",  "Paychex",                                "Industrials",            "Human Resource & Employment Services"),
    Stock("PCAR",  "Paccar",                                 "Industrials",            "Construction Machinery & Heavy Transportation Equipment"),
    Stock("PH",    "Parker Hannifin",                        "Industrials",            "Industrial Machinery & Supplies & Components"),
    Stock("PNR",   "Pentair",                                "Industrials",            "Industrial Machinery & Supplies & Components"),
    Stock("PWR",   "Quanta Services",                        "Industrials",            "Construction & Engineering"),
    Stock("ROK",   "Rockwell Automation",                    "Industrials",            "Electrical Components & Equipment"),
    Stock("ROL",   "Rollins, Inc.",                          "Industrials",            "Environmental & Facilities Services"),
    Stock("RSG",   "Republic Services",                      "Industrials",            "Environmental & Facilities Services"),
    Stock("RTX",   "RTX Corporation",                        "Industrials",            "Aerospace & Defense"),
    Stock("SNA",   "Snap-on",                                "Industrials",            "Industrial Machinery & Supplies & Components"),
    Stock("SWK",   "Stanley Black & Decker",                 "Industrials",            "Industrial Machinery & Supplies & Components"),
    Stock("TDG",   "TransDigm Group",                        "Industrials",            "Aerospace & Defense"),
    Stock("TT",    "Trane Technologies",                     "Industrials",            "Building Products"),
    Stock("TXT",   "Textron",                                "Industrials",            "Aerospace & Defense"),
    Stock("UAL",   "United Airlines Holdings",               "Industrials",            "Passenger Airlines"),
    Stock("UBER",  "Uber",                                   "Industrials",            "Passenger Ground Transportation"),
    Stock("UNP",   "Union Pacific Corporation",              "Industrials",            "Rail Transportation"),
    Stock("UPS",   "United Parcel Service",                  "Industrials",            "Air Freight & Logistics"),
    Stock("URI",   "United Rentals",                         "Industrials",            "Trading Companies & Distributors"),
    Stock("VLTO",  "Veralto",                                "Industrials",            "Environmental & Facilities Services"),
    Stock("VRSK",  "Verisk Analytics",                       "Industrials",            "Research & Consulting Services"),
    Stock("VRT",   "Vertiv",                                 "Industrials",            "Electrical Components & Equipment"),
    Stock("WAB",   "Wabtec",                                 "Industrials",            "Construction Machinery & Heavy Transportation Equipment"),
    Stock("WM",    "Waste Management",                       "Industrials",            "Environmental & Facilities Services"),
    Stock("XYL",   "Xylem Inc.",                             "Industrials",            "Industrial Machinery & Supplies & Components"),

    # ── Energy (22) ──
    Stock("APA",   "APA Corporation",                        "Energy",                 "Oil & Gas Exploration & Production"),
    Stock("BKR",   "Baker Hughes",                           "Energy",                 "Oil & Gas Equipment & Services"),
    Stock("COP",   "ConocoPhillips",                         "Energy",                 "Oil & Gas Exploration & Production"),
    Stock("CTRA",  "Coterra",                                "Energy",                 "Oil & Gas Exploration & Production"),
    Stock("CVX",   "Chevron Corporation",                    "Energy",                 "Integrated Oil & Gas"),
    Stock("DVN",   "Devon Energy",                           "Energy",                 "Oil & Gas Exploration & Production"),
    Stock("EOG",   "EOG Resources",                          "Energy",                 "Oil & Gas Exploration & Production"),
    Stock("EQT",   "EQT Corporation",                        "Energy",                 "Oil & Gas Exploration & Production"),
    Stock("EXE",   "Expand Energy",                          "Energy",                 "Oil & Gas Exploration & Production"),
    Stock("FANG",  "Diamondback Energy",                     "Energy",                 "Oil & Gas Exploration & Production"),
    Stock("HAL",   "Halliburton",                            "Energy",                 "Oil & Gas Equipment & Services"),
    Stock("KMI",   "Kinder Morgan",                          "Energy",                 "Oil & Gas Storage & Transportation"),
    Stock("MPC",   "Marathon Petroleum",                     "Energy",                 "Oil & Gas Refining & Marketing"),
    Stock("OKE",   "Oneok",                                  "Energy",                 "Oil & Gas Storage & Transportation"),
    Stock("OXY",   "Occidental Petroleum",                   "Energy",                 "Oil & Gas Exploration & Production"),
    Stock("PSX",   "Phillips 66",                            "Energy",                 "Oil & Gas Refining & Marketing"),
    Stock("SLB",   "Schlumberger",                           "Energy",                 "Oil & Gas Equipment & Services"),
    Stock("TPL",   "Texas Pacific Land Corporation",         "Energy",                 "Oil & Gas Exploration & Production"),
    Stock("TRGP",  "Targa Resources",                        "Energy",                 "Oil & Gas Storage & Transportation"),
    Stock("VLO",   "Valero Energy",                          "Energy",                 "Oil & Gas Refining & Marketing"),
    Stock("WMB",   "Williams Companies",                     "Energy",                 "Oil & Gas Storage & Transportation"),
    Stock("XOM",   "ExxonMobil",                             "Energy",                 "Integrated Oil & Gas"),

    # ── Materials (26) ──
    Stock("ALB",   "Albemarle Corporation",                  "Materials",              "Specialty Chemicals"),
    Stock("AMCR",  "Amcor",                                  "Materials",              "Paper & Plastic Packaging Products & Materials"),
    Stock("APD",   "Air Products",                           "Materials",              "Industrial Gases"),
    Stock("AVY",   "Avery Dennison",                         "Materials",              "Paper & Plastic Packaging Products & Materials"),
    Stock("BALL",  "Ball Corporation",                       "Materials",              "Metal, Glass & Plastic Containers"),
    Stock("CF",    "CF Industries",                          "Materials",              "Fertilizers & Agricultural Chemicals"),
    Stock("CRH",   "CRH plc",                                "Materials",              "Construction Materials"),
    Stock("CTVA",  "Corteva",                                "Materials",              "Fertilizers & Agricultural Chemicals"),
    Stock("DD",    "DuPont",                                 "Materials",              "Specialty Chemicals"),
    Stock("DOW",   "Dow Inc.",                               "Materials",              "Commodity Chemicals"),
    Stock("ECL",   "Ecolab",                                 "Materials",              "Specialty Chemicals"),
    Stock("FCX",   "Freeport-McMoRan",                       "Materials",              "Copper"),
    Stock("IFF",   "International Flavors & Fragrances",     "Materials",              "Specialty Chemicals"),
    Stock("IP",    "International Paper",                    "Materials",              "Paper & Plastic Packaging Products & Materials"),
    Stock("LIN",   "Linde plc",                              "Materials",              "Industrial Gases"),
    Stock("LYB",   "LyondellBasell",                         "Materials",              "Specialty Chemicals"),
    Stock("MLM",   "Martin Marietta Materials",              "Materials",              "Construction Materials"),
    Stock("MOS",   "Mosaic Company (The)",                   "Materials",              "Fertilizers & Agricultural Chemicals"),
    Stock("NEM",   "Newmont",                                "Materials",              "Gold"),
    Stock("NUE",   "Nucor",                                  "Materials",              "Steel"),
    Stock("PKG",   "Packaging Corporation of America",       "Materials",              "Paper & Plastic Packaging Products & Materials"),
    Stock("PPG",   "PPG Industries",                         "Materials",              "Specialty Chemicals"),
    Stock("SHW",   "Sherwin-Williams",                       "Materials",              "Specialty Chemicals"),
    Stock("STLD",  "Steel Dynamics",                         "Materials",              "Steel"),
    Stock("SW",    "Smurfit Westrock",                       "Materials",              "Paper & Plastic Packaging Products & Materials"),
    Stock("VMC",   "Vulcan Materials Company",               "Materials",              "Construction Materials"),

    # ── Real Estate (31) ──
    Stock("AMT",   "American Tower",                         "Real Estate",            "Telecom Tower REITs"),
    Stock("ARE",   "Alexandria Real Estate Equities",        "Real Estate",            "Office REITs"),
    Stock("AVB",   "AvalonBay Communities",                  "Real Estate",            "Multi-Family Residential REITs"),
    Stock("BXP",   "BXP, Inc.",                              "Real Estate",            "Office REITs"),
    Stock("CBRE",  "CBRE Group",                             "Real Estate",            "Real Estate Services"),
    Stock("CCI",   "Crown Castle",                           "Real Estate",            "Telecom Tower REITs"),
    Stock("CPT",   "Camden Property Trust",                  "Real Estate",            "Multi-Family Residential REITs"),
    Stock("CSGP",  "CoStar Group",                           "Real Estate",            "Real Estate Services"),
    Stock("DLR",   "Digital Realty",                         "Real Estate",            "Data Center REITs"),
    Stock("DOC",   "Healthpeak Properties",                  "Real Estate",            "Health Care REITs"),
    Stock("EQIX",  "Equinix",                                "Real Estate",            "Data Center REITs"),
    Stock("EQR",   "Equity Residential",                     "Real Estate",            "Multi-Family Residential REITs"),
    Stock("ESS",   "Essex Property Trust",                   "Real Estate",            "Multi-Family Residential REITs"),
    Stock("EXR",   "Extra Space Storage",                    "Real Estate",            "Self-Storage REITs"),
    Stock("FRT",   "Federal Realty Investment Trust",        "Real Estate",            "Retail REITs"),
    Stock("HST",   "Host Hotels & Resorts",                  "Real Estate",            "Hotel & Resort REITs"),
    Stock("INVH",  "Invitation Homes",                       "Real Estate",            "Single-Family Residential REITs"),
    Stock("IRM",   "Iron Mountain",                          "Real Estate",            "Other Specialized REITs"),
    Stock("KIM",   "Kimco Realty",                           "Real Estate",            "Retail REITs"),
    Stock("MAA",   "Mid-America Apartment Communities",      "Real Estate",            "Multi-Family Residential REITs"),
    Stock("O",     "Realty Income",                          "Real Estate",            "Retail REITs"),
    Stock("PLD",   "Prologis",                               "Real Estate",            "Industrial REITs"),
    Stock("PSA",   "Public Storage",                         "Real Estate",            "Self-Storage REITs"),
    Stock("REG",   "Regency Centers",                        "Real Estate",            "Retail REITs"),
    Stock("SBAC",  "SBA Communications",                     "Real Estate",            "Telecom Tower REITs"),
    Stock("SPG",   "Simon Property Group",                   "Real Estate",            "Retail REITs"),
    Stock("UDR",   "UDR, Inc.",                              "Real Estate",            "Multi-Family Residential REITs"),
    Stock("VICI",  "Vici Properties",                        "Real Estate",            "Hotel & Resort REITs"),
    Stock("VTR",   "Ventas",                                 "Real Estate",            "Health Care REITs"),
    Stock("WELL",  "Welltower",                              "Real Estate",            "Health Care REITs"),
    Stock("WY",    "Weyerhaeuser",                           "Real Estate",            "Timber REITs"),

    # ── Utilities (31) ──
    Stock("AEE",   "Ameren",                                 "Utilities",              "Multi-Utilities"),
    Stock("AEP",   "American Electric Power",                "Utilities",              "Electric Utilities"),
    Stock("AES",   "AES Corporation",                        "Utilities",              "Independent Power Producers & Energy Traders"),
    Stock("ATO",   "Atmos Energy",                           "Utilities",              "Gas Utilities"),
    Stock("AWK",   "American Water Works",                   "Utilities",              "Water Utilities"),
    Stock("CEG",   "Constellation Energy",                   "Utilities",              "Electric Utilities"),
    Stock("CMS",   "CMS Energy",                             "Utilities",              "Multi-Utilities"),
    Stock("CNP",   "CenterPoint Energy",                     "Utilities",              "Multi-Utilities"),
    Stock("D",     "Dominion Energy",                        "Utilities",              "Multi-Utilities"),
    Stock("DTE",   "DTE Energy",                             "Utilities",              "Multi-Utilities"),
    Stock("DUK",   "Duke Energy",                            "Utilities",              "Electric Utilities"),
    Stock("ED",    "Consolidated Edison",                    "Utilities",              "Multi-Utilities"),
    Stock("EIX",   "Edison International",                   "Utilities",              "Electric Utilities"),
    Stock("ES",    "Eversource Energy",                      "Utilities",              "Electric Utilities"),
    Stock("ETR",   "Entergy",                                "Utilities",              "Electric Utilities"),
    Stock("EVRG",  "Evergy",                                 "Utilities",              "Electric Utilities"),
    Stock("EXC",   "Exelon",                                 "Utilities",              "Electric Utilities"),
    Stock("FE",    "FirstEnergy",                            "Utilities",              "Electric Utilities"),
    Stock("LNT",   "Alliant Energy",                         "Utilities",              "Electric Utilities"),
    Stock("NEE",   "NextEra Energy",                         "Utilities",              "Multi-Utilities"),
    Stock("NI",    "NiSource",                               "Utilities",              "Multi-Utilities"),
    Stock("NRG",   "NRG Energy",                             "Utilities",              "Independent Power Producers & Energy Traders"),
    Stock("PCG",   "PG&E Corporation",                       "Utilities",              "Multi-Utilities"),
    Stock("PEG",   "Public Service Enterprise Group",        "Utilities",              "Electric Utilities"),
    Stock("PNW",   "Pinnacle West Capital",                  "Utilities",              "Multi-Utilities"),
    Stock("PPL",   "PPL Corporation",                        "Utilities",              "Electric Utilities"),
    Stock("SO",    "Southern Company",                       "Utilities",              "Electric Utilities"),
    Stock("SRE",   "Sempra",                                 "Utilities",              "Multi-Utilities"),
    Stock("VST",   "Vistra Corp.",                           "Utilities",              "Electric Utilities"),
    Stock("WEC",   "WEC Energy Group",                       "Utilities",              "Electric Utilities"),
    Stock("XEL",   "Xcel Energy",                            "Utilities",              "Multi-Utilities"),
]


# Aux tickers — visible in explorer, excluded from UNIVERSE so autoResearch
# pooled model training stays pure S&P 500 constituents.
AUX: list[Stock] = [
    Stock("SPX", "S&P 500 Index", "Index", "US Equity Index"),
]


_BY_TICKER: dict[str, Stock] = {s.ticker: s for s in UNIVERSE + AUX}


def tickers() -> list[str]:
    return [s.ticker for s in UNIVERSE]


def get(ticker: str) -> Stock | None:
    return _BY_TICKER.get(ticker.upper())


def is_known(ticker: str) -> bool:
    return ticker.upper() in _BY_TICKER


def by_sector() -> "OrderedDict[str, list[Stock]]":
    """Return {sector → [Stock, …]} in SECTOR_ORDER."""
    buckets: dict[str, list[Stock]] = {}
    for s in list(UNIVERSE) + list(AUX):
        buckets.setdefault(s.sector, []).append(s)
    out: "OrderedDict[str, list[Stock]]" = OrderedDict()
    for sec in SECTOR_ORDER:
        if sec in buckets:
            out[sec] = sorted(buckets.pop(sec), key=lambda s: s.ticker)
    for sec in sorted(buckets):
        out[sec] = sorted(buckets[sec], key=lambda s: s.ticker)
    return out


def by_industry(sector: str | None = None) -> "OrderedDict[str, list[Stock]]":
    """Return {sub-industry → [Stock, …]}. If `sector` is given, restrict to it."""
    buckets: dict[str, list[Stock]] = {}
    for s in UNIVERSE:
        if sector and s.sector != sector:
            continue
        buckets.setdefault(s.industry, []).append(s)
    return OrderedDict(
        (ind, sorted(buckets[ind], key=lambda s: s.ticker))
        for ind in sorted(buckets)
    )
